apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: shiny-server
  annotations:
    description: "Template for deployment of R-Shiny applications.\n For more info see https://github.com/ResearchIT/docker-shiny-server"
    iconClass: "icon-other-unknown"
    tags: "shiny,r,r-shiny"
    template.openshift.io/bindable: "false"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - name: shiny-web
      port: 3838
      targetPort: 3838
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the application server
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: ${NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - image: docker-registry.default.svc:5000/shiny-server/
          imagePullPolicy: Always
          name: ${NAME}
          ports:
          - containerPort: 3838
          resources:
            limits:
              memory: 1G
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    metadata:
    annotations:
      description: Defines how to build the application
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: "${CONTEXT_DIR}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: researchit/shiny-server:latest
        forcePull: true
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}

parameters:
  - name: NAME
    displayName: Name 
    description: The name assigned to all frontend objects defined in this template. 
    value: shiny-server 
    required: true 
  - name: SOURCE_REPOSITORY_URL 
    displayName: Source Repository URL 
    description: The URL of the repository with your application source code 
    value: https://github.com/researchit/shiny-ex.git 
    required: true 
  - name: SOURCE_REPOSITORY_REF 
    displayName: Source Repository Reference
    description: The branch or tag of the repository with your application source code 
    value: master
    required: false
  - name: CONTEXT_DIR
    displayName: Source Repository application root directory
    description: The directory within your repository with your application source code 
    value: ""
    required: false